import {
  BarChart3,
  Bell,
  Cat,
  Home,
  Megaphone,
  Monitor,
  Package,
  PawPrint,
  Settings,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Store,
  User,
  Video,
} from "lucide-react";
import type { NavItem } from "./nav-utils";

export const navItems: NavItem[] = [
  {
    key: "overview",
    labelKey: "nav.start",
    href: "/",
    icon: Home,
  },
  {
    key: "myArea",
    labelKey: "nav.myArea",
    href: "/mein-bereich",
    icon: User,
    requiredPermissions: ["manage_integrations"],
  },
  {
    key: "amazon",
    labelKey: "nav.amazon",
    href: "/amazon",
    icon: ShoppingCart,
    requiredPermissions: ["manage_integrations"],
    children: [
      { labelKey: "nav.amazonOrders", href: "/amazon/orders" },
      { labelKey: "nav.amazonProducts", href: "/amazon/products" },
    ],
  },
  {
    key: "ebay",
    labelKey: "nav.ebay",
    href: "/ebay",
    icon: ShoppingBag,
    requiredPermissions: ["manage_integrations"],
    children: [
      { labelKey: "nav.ebayOrders", href: "/ebay/orders" },
      { labelKey: "nav.ebayProducts", href: "/ebay/products" },
    ],
  },
  {
    key: "otto",
    labelKey: "nav.otto",
    href: "/otto",
    icon: ShoppingBag,
    requiredPermissions: ["manage_integrations"],
    children: [
      { labelKey: "nav.ottoOrders", href: "/otto/orders" },
      { labelKey: "nav.ottoProducts", href: "/otto/products" },
    ],
  },
  {
    key: "kaufland",
    labelKey: "nav.kaufland",
    href: "/kaufland",
    icon: Store,
    requiredPermissions: ["manage_integrations"],
    children: [
      { labelKey: "nav.kauflandOrders", href: "/kaufland/orders" },
      { labelKey: "nav.kauflandProducts", href: "/kaufland/products" },
    ],
  },
  {
    key: "fressnapf",
    labelKey: "nav.fressnapf",
    href: "/fressnapf",
    icon: PawPrint,
    requiredPermissions: ["manage_integrations"],
    children: [
      { labelKey: "nav.fressnapfOrders", href: "/fressnapf/orders" },
      { labelKey: "nav.fressnapfProducts", href: "/fressnapf/products" },
    ],
  },
  {
    key: "mediamarktSaturn",
    labelKey: "nav.mediamarktSaturn",
    href: "/mediamarkt-saturn",
    icon: Monitor,
    requiredPermissions: ["manage_integrations"],
    children: [
      { labelKey: "nav.mediamarktSaturnOrders", href: "/mediamarkt-saturn/orders" },
      { labelKey: "nav.mediamarktSaturnProducts", href: "/mediamarkt-saturn/products" },
    ],
  },
  {
    key: "zooplus",
    labelKey: "nav.zooplus",
    href: "/zooplus",
    icon: Cat,
    requiredPermissions: ["manage_integrations"],
    children: [
      { labelKey: "nav.zooplusOrders", href: "/zooplus/orders" },
      { labelKey: "nav.zooplusProducts", href: "/zooplus/products" },
    ],
  },
  {
    key: "tiktok",
    labelKey: "nav.tiktok",
    href: "/tiktok",
    icon: Video,
    requiredPermissions: ["manage_integrations"],
    children: [
      { labelKey: "nav.tiktokOrders", href: "/tiktok/orders" },
      { labelKey: "nav.tiktokProducts", href: "/tiktok/products" },
    ],
  },
  {
    key: "shopify",
    labelKey: "nav.shopify",
    href: "/shopify",
    icon: ShoppingBasket,
    requiredPermissions: ["manage_integrations"],
    children: [
      { labelKey: "nav.shopifyOrders", href: "/shopify/orders" },
      { labelKey: "nav.shopifyProducts", href: "/shopify/products" },
    ],
  },
  {
    key: "xentral",
    labelKey: "nav.xentral",
    href: "/xentral",
    icon: Package,
    requiredPermissions: ["manage_integrations"],
    children: [
      { labelKey: "nav.xentralProducts", href: "/xentral/products" },
      { labelKey: "nav.xentralOrders", href: "/xentral/orders" },
    ],
  },
  {
    key: "advertising",
    labelKey: "nav.advertising",
    href: "/advertising",
    icon: Megaphone,
    requiredPermissions: ["manage_integrations"],
    children: [
      { labelKey: "nav.adCampaigns", href: "/advertising/campaigns" },
      { labelKey: "nav.adPerformance", href: "/advertising/performance" },
    ],
  },
  {
    key: "analytics",
    labelKey: "nav.analytics",
    href: "/analytics",
    icon: BarChart3,
    requiredPermissions: ["export_data"],
    children: [
      { labelKey: "nav.analyticsMarketplaces", href: "/analytics/marketplaces" },
      { labelKey: "nav.analyticsPayouts", href: "/analytics/payouts" },
      { labelKey: "nav.analyticsArticleForecast", href: "/analytics/article-forecast" },
      { labelKey: "nav.analyticsProcurement", href: "/analytics/procurement" },
    ],
  },
  {
    key: "settings",
    labelKey: "nav.settings",
    href: "/settings",
    icon: Settings,
    children: [
      { labelKey: "nav.settingsUsers", href: "/settings/users" },
      { labelKey: "nav.settingsProfile", href: "/settings/profile" },
      { labelKey: "nav.settingsTutorials", href: "/settings/tutorials" },
    ],
  },
  {
    key: "updates",
    labelKey: "nav.updates",
    href: "/updates",
    icon: Bell,
  },
];
